phantomjs:
  image: patton/pyspider:0.1
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json phantomjs
result:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json result_worker
processor:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json processor
fetcher:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  links:
    - phantomjs
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json fetcher
scheduler:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json scheduler
webui:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  links:
    - scheduler
    - phantomjs
  volumes: 
    - ./config.json:/root/config.json
  command: -c /root/config.json webui
  ports:
    - "5000:5000"