phantomjs:
  image: patton/pyspider:0.1
  volume: ./config.json:/root/config.json
  command: -c /root/config.json phantomjs
result:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  volume: ./config.json:/root/config.json
  command: -c /root/config.json result_worker
processor:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  volume: ./config.json:/root/config.json
  command: -c /root/config.json processor
fetcher:
  image: patton/pyspider:0.1
  external_links:
    - rabbitmq
  links:
    - phantomjs
  volume: ./config.json:/root/config.json
  command: -c /root/config.json fetcher
scheduler:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  command: scheduler
webui:
  image: patton/pyspider:0.1
  external_links:
    - mysql
    - rabbitmq
  links:
    - scheduler
    - phantomjs
  volume: ./config.json:/root/config.json
  command: -c /root/config.json webui
  ports:
    - "5000:5000"
pyspider:
  image: patton/pyspider:0.1
  volume: ./config.json:/root/config.json
  command: -c /root/config.json
  links:
    - mysql
    - rabbitmq
  ports:
    - "5000:5000"