mysql:
  image: mysql:5.7.18
  container_name: mysql5.7
  volumes:
    - /data/mysql:/var/lib/mysql
    - ./conf:/etc/mysql/conf.d
  restart:  always
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mysql
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
  ports:
    - 3306:3306
