redis:
  image: redis:latest
  ports:
    - 6379:6379
mysql:
  image: mysql:5.7.18
  container_name: mysql5.7
  volumes:
    - /data/mysqltmp:/var/lib/mysql
    - ./conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mysql
    - MYSQL_USER=mysql
    - MYSQL_PASSWORD=mysql
  ports:
    - 3307:3306
scheduler:
  image: 'patton/pyspider:0.1'
  command: '--taskdb "mysql+taskdb://root:root@mysql:3306/taskdb"  --projectdb "mysql+projectdb://root:root@mysql:3306/projectdb" --resultdb "mysql+resultdb://root:root@mysql:3306/resultdb" --message-queue "redis://redis:6379/1"  scheduler --inqueue-limit 5000 --delete-time 43200'
  cpu_shares: 512
  links:
    - mysql
    - redis
  environment:
    - 'EXCLUDE_PORTS=5000,25555'
  restart: always 
phantomjs:
  image: 'patton/pyspider:0.1'
  command: phantomjs
  cpu_shares: 512
  environment:
    - 'EXCLUDE_PORTS=5000,23333,24444'
  expose:
    - '25555'
  mem_limit: 512m
  restart: always
phantomjs-lb:
  image: 'dockercloud/haproxy:latest'
  links:
    - phantomjs
  restart: always
fetcher:
  image: 'patton/pyspider:0.1'
  command: '--message-queue "redis://mysql:6379/1" --phantomjs-proxy "phantomjs:80" fetcher --xmlrpc'
  cpu_shares: 512
  environment:
    - 'EXCLUDE_PORTS=5000,25555,23333'
  links:
    - 'phantomjs-lb:phantomjs'
  mem_limit: 128m
  restart: always
fetcher-lb:
  image: 'dockercloud/haproxy:latest'
  links:
    - fetcher
  restart: always
processor:
  image: 'patton/pyspider:0.1'
  command: '--projectdb "mysql+projectdb://root:root@mysql:3306/projectdb" --message-queue "redis://redis:6379/1" processor'
  links:
    - redis
  cpu_shares: 512
  mem_limit: 256m
  restart: always
result-worker:
  image: 'patton/pyspider:0.1'
  command: '--taskdb "mysql+taskdb://root:root@mysql:3306/taskdb"  --projectdb "mysql+projectdb://root:root@mysql:3306/projectdb" --resultdb "mysql+resultdb://root:root@mysql:3306/resultdb" --message-queue "redis://redis:6379/1" result_worker'
  links:
    - mysql
    - redis
  cpu_shares: 512
  mem_limit: 256m
  restart: always
webui:
  image: 'patton/pyspider:0.1'
  command: '--taskdb "mysql+taskdb://root:root@mysql:3306/taskdb"  --projectdb "mysql+projectdb://root:root@mysql:3306/projectdb" --resultdb "mysql+resultdb://root:root@mysql:3306/resultdb" --message-queue "redis://redis:6379/1" webui --max-rate 0.2 --max-burst 3 --scheduler-rpc "http://o4.i.binux.me:23333/" --fetcher-rpc "http://fetcher/"'
  cpu_shares: 512
  environment:
    - 'EXCLUDE_PORTS=24444,25555,23333'
  links:
    - 'fetcher-lb:fetcher'
    - mysql
    - redis
  mem_limit: 256m
  restart: always
webui-lb:
  image: 'dockercloud/haproxy:latest'
  links:
    - webui
  restart: always
nginx:
  image: 'nginx'
  links:
    - 'webui-lb:HAPROXY'
  ports:
    - '0.0.0.0:80:80'
  volumes:
    - /home/binux/nfs/profile/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /home/binux/nfs/profile/nginx/conf.d/:/etc/nginx/conf.d/
  restart: always