# mysql
mysql:
  image: mysql:latest
  container_name: mysql
  volumes: /data/mysql:/var/lib/mysql
  ports: 
    - 3306:3306
  environment: 
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
rabbitmq:
  image: rabbitmq:latest
  container_name: rabbitmq
phantomjs:
  image: binux/pyspider:latest
  command: phantomjs
result:
  image: binux/pyspider:latest
  links:
    - mysql
    - rabbitmq
  command: result_worker
processor:
  image: binux/pyspider:latest
  links:
    - mysql
    - rabbitmq
  command: processor
fetcher:
  image: binux/pyspider:latest
  links:
    - rabbitmq
    - phantomjs
  command : fetcher
scheduler:
  image: binux/pyspider:latest
  links:
    - mysql
    - rabbitmq
  command: scheduler
webui:
  image: binux/pyspider:latest
  links:
    - mysql
    - rabbitmq
    - scheduler
    - phantomjs
  command: webui
  ports:
    - "5000:5000"