phantomjs:
  image: binux/pyspider:latest
  command: phantomjs
result:
  image: binux/pyspider:latest
  external_links:
    - mysql_mysql_1:mysql
    - redis_redis_1:redis
  command: result_worker
processor:
  image: binux/pyspider:latest
  external_links:
    - mysql_mysql_1:mysql
    - redis_redis_1:redis
  command: processor
fetcher:
  image: binux/pyspider:latest
  external_links:
    - redis_redis_1:redis
  links:
    - phantomjs
  command : fetcher
scheduler:
  image: binux/pyspider:latest
  external_links:
    - mysql_mysql_1:mysql
    - redis_redis_1:redis
  command: scheduler
webui:
  image: binux/pyspider:latest
  external_links:
    - mysql_mysql_1:mysql
    - redis_redis_1:redis
  links:
    - scheduler
    - phantomjs
  command: webui
  ports:
    - "5000:5000"