postgres:
  image: postgres:9.6.3
  container_name: postgres9.6
  volumes:
    - /data/postgres:/var/lib/postgresql/data
#    - ./conf:/etc/mysql/conf.d
  restart:  always
  environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=mysql
  ports:
    - 5432:5432
