pd1:
    image: pingcap/pd:latest
#    restart: always
    expose:
        - "2379"
        - "2380"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --name="pd1" --data-dir="/data/pd1" --client-urls="http://pd1:2379" --advertise-client-urls="http://pd1:2379" --peer-urls="http://pd1:2380" --advertise-peer-urls="http://pd1:2380" --initial-cluster="pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380"

pd2:
    image: pingcap/pd:latest
#    restart: always
    expose:
        - "2379"
        - "2380"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --name="pd2" --data-dir="/data/pd2" --client-urls="http://pd2:2379" --advertise-client-urls="http://pd2:2379" --peer-urls="http://pd2:2380" --advertise-peer-urls="http://pd2:2380" --initial-cluster="pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380"
pd3:
    image: pingcap/pd:latest
#    restart: always
    expose:
        - "2379"
        - "2380"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --name="pd3" --data-dir="/data/pd3" --client-urls="http://pd3:2379" --advertise-client-urls="http://pd3:2379" --peer-urls="http://pd3:2380" --advertise-peer-urls="http://pd3:2380" --initial-cluster="pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380"
tikv1:
    image: pingcap/tikv:latest
#    restart: always
    expose:
        - "20160"
    links:
        - pd1
        - pd2
        - pd3
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --addr="tikv1:20160" --advertise-addr="tikv1:20160" --data-dir="/data/tikv1" --pd="pd1:2379,pd1:2379,pd3:2379"
tikv2:
    image: pingcap/tikv:latest
#    restart: always
    expose:
        - "20160"
    links:
        - pd1
        - pd2
        - pd3
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --addr="tikv2:20160" --advertise-addr="tikv2:20160" --data-dir="/data/tikv2" --pd="pd1:2379,pd1:2379,pd3:2379"
tikv3:
    image: pingcap/tikv:latest
#    restart: always
    expose:
        - "20160"
    links:
        - pd1
        - pd2
        - pd3
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data:/data
    command: --addr="tikv3:20160" --advertise-addr="tikv3:20160" --data-dir="/data/tikv3" --pd="pd1:2379,pd1:2379,pd3:2379"
tidb:
    image: pingcap/tidb:latest
#    restart: always
    ports:
        - "4000:4000"
        - "10080:10080"
    links:
        - pd1
        - pd2
        - pd3
    volumes:
        - /etc/localtime:/etc/localtime:ro
    command: --store=tikv --path="pd1:2379,pd2:2379,pd3:2379"