rabbitmq:
  image: rabbitmq:3-management
  volumes:
    - /data/rabbitmq:/var/lib/rabbitmq
  restart:  always
  envirements:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  ports:
    - 5671:5671
    - 5672:5672
    - 15671:15671
    - 15672:15672
    - 25672:25672
    - 4370:4369
    - 8080:15672
# managment user&pw:admin/admin