data1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: data1_phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /software/phpmyadmin/conf/config.inc.php:/etc/phpmyadmin/config.inc.php
